import type { DriverReport } from "../../../interfaces/driver";

export const mockedDriverReports: DriverReport[] = [
  {
    name: "João da Silva",
    points: 85,
    bonus: 500,
    totalOccurrences: 5,
    totalUnresolvedOccurrences: 1,
    topOccurrence: "Atraso na linha",
    occurrenceSource: "Fiscal de Linha",
  },
  {
    name: "Carlos de Souza",
    points: 92,
    bonus: 750,
    totalOccurrences: 2,
    totalUnresolvedOccurrences: 0,
    topOccurrence: "Congestionamento",
    occurrenceSource: "GPS",
  },
  {
    name: "Pedro Oliveira",
    points: 70,
    bonus: 200,
    totalOccurrences: 10,
    totalUnresolvedOccurrences: 3,
    topOccurrence: "Problema mecânico",
    occurrenceSource: "Motorista",
  },
  {
    name: "Lucas Martins",
    points: 98,
    bonus: 1000,
    totalOccurrences: 1,
    totalUnresolvedOccurrences: 0,
    topOccurrence: "Pneu furado",
    occurrenceSource: "Motorista",
  },
  {
    name: "Matheus Pereira",
    points: 60,
    bonus: 100,
    totalOccurrences: 15,
    totalUnresolvedOccurrences: 5,
    topOccurrence: "Acidente na via",
    occurrenceSource: "Polícia Militar",
  },
  {
    name: "Gabriel Alves",
    points: 78,
    bonus: 400,
    totalOccurrences: 7,
    totalUnresolvedOccurrences: 2,
    topOccurrence: "Assalto no ônibus",
    occurrenceSource: "Passageiro",
  },
];
