FROM mongo:latest

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=adminedurod
ENV MONGO_INITDB_ROOT_PASSWORD=edurodpassword2025

# Expose MongoDB port
EXPOSE 27017

# Use the default MongoDB entrypoint
CMD ["mongod"]